//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb_FrutosFrescos.wsFrutos2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wspack/", ConfigurationName="wsFrutos2.wsFrutos2")]
    public interface wsFrutos2 {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://wspack/).
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/insDetalleRequest", ReplyAction="http://wspack/wsFrutos2/insDetalleResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppWeb_FrutosFrescos.wsFrutos2.insDetalleResponse insDetalle(AppWeb_FrutosFrescos.wsFrutos2.insDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/insDetalleRequest", ReplyAction="http://wspack/wsFrutos2/insDetalleResponse")]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.insDetalleResponse> insDetalleAsync(AppWeb_FrutosFrescos.wsFrutos2.insDetalleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://wspack/).
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/delVentaRequest", ReplyAction="http://wspack/wsFrutos2/delVentaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppWeb_FrutosFrescos.wsFrutos2.delVentaResponse delVenta(AppWeb_FrutosFrescos.wsFrutos2.delVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/delVentaRequest", ReplyAction="http://wspack/wsFrutos2/delVentaResponse")]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.delVentaResponse> delVentaAsync(AppWeb_FrutosFrescos.wsFrutos2.delVentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://wspack/).
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/delDetalleRequest", ReplyAction="http://wspack/wsFrutos2/delDetalleResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppWeb_FrutosFrescos.wsFrutos2.delDetalleResponse delDetalle(AppWeb_FrutosFrescos.wsFrutos2.delDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/delDetalleRequest", ReplyAction="http://wspack/wsFrutos2/delDetalleResponse")]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.delDetalleResponse> delDetalleAsync(AppWeb_FrutosFrescos.wsFrutos2.delDetalleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/getDetalleByIdRequest", ReplyAction="http://wspack/wsFrutos2/getDetalleByIdResponse")]
        AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdResponse getDetalleById(AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/getDetalleByIdRequest", ReplyAction="http://wspack/wsFrutos2/getDetalleByIdResponse")]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdResponse> getDetalleByIdAsync(AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://wspack/).
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/updDetalleRequest", ReplyAction="http://wspack/wsFrutos2/updDetalleResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppWeb_FrutosFrescos.wsFrutos2.updDetalleResponse updDetalle(AppWeb_FrutosFrescos.wsFrutos2.updDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/updDetalleRequest", ReplyAction="http://wspack/wsFrutos2/updDetalleResponse")]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.updDetalleResponse> updDetalleAsync(AppWeb_FrutosFrescos.wsFrutos2.updDetalleRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/ListarDetalleByIdVentaRequest", ReplyAction="http://wspack/wsFrutos2/ListarDetalleByIdVentaResponse")]
        AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaResponse ListarDetalleByIdVenta(AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/ListarDetalleByIdVentaRequest", ReplyAction="http://wspack/wsFrutos2/ListarDetalleByIdVentaResponse")]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaResponse> ListarDetalleByIdVentaAsync(AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/getProductoUsuarioRequest", ReplyAction="http://wspack/wsFrutos2/getProductoUsuarioResponse")]
        AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioResponse getProductoUsuario(AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/getProductoUsuarioRequest", ReplyAction="http://wspack/wsFrutos2/getProductoUsuarioResponse")]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioResponse> getProductoUsuarioAsync(AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/getStockByIdRequest", ReplyAction="http://wspack/wsFrutos2/getStockByIdResponse")]
        AppWeb_FrutosFrescos.wsFrutos2.getStockByIdResponse getStockById(AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/getStockByIdRequest", ReplyAction="http://wspack/wsFrutos2/getStockByIdResponse")]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getStockByIdResponse> getStockByIdAsync(AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/getStockRequest", ReplyAction="http://wspack/wsFrutos2/getStockResponse")]
        AppWeb_FrutosFrescos.wsFrutos2.getStockResponse getStock(AppWeb_FrutosFrescos.wsFrutos2.getStockRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos2/getStockRequest", ReplyAction="http://wspack/wsFrutos2/getStockResponse")]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getStockResponse> getStockAsync(AppWeb_FrutosFrescos.wsFrutos2.getStockRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insDetalle", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class insDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int Total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int IdStock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int IdVenta;
        
        public insDetalleRequest() {
        }
        
        public insDetalleRequest(int Cantidad, int Total, int IdStock, int IdVenta) {
            this.Cantidad = Cantidad;
            this.Total = Total;
            this.IdStock = IdStock;
            this.IdVenta = IdVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insDetalleResponse", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class insDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public insDetalleResponse() {
        }
        
        public insDetalleResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delVenta", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class delVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Id;
        
        public delVentaRequest() {
        }
        
        public delVentaRequest(int Id) {
            this.Id = Id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delVentaResponse", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class delVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public delVentaResponse() {
        }
        
        public delVentaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delDetalle", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class delDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int id;
        
        public delDetalleRequest() {
        }
        
        public delDetalleRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delDetalleResponse", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class delDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public delDetalleResponse() {
        }
        
        public delDetalleResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetalleByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetalleById", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequestBody Body;
        
        public getDetalleByIdRequest() {
        }
        
        public getDetalleByIdRequest(AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDetalleByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdDetalle;
        
        public getDetalleByIdRequestBody() {
        }
        
        public getDetalleByIdRequestBody(int IdDetalle) {
            this.IdDetalle = IdDetalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDetalleByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDetalleByIdResponse", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdResponseBody Body;
        
        public getDetalleByIdResponse() {
        }
        
        public getDetalleByIdResponse(AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getDetalleByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getDetalleByIdResponseBody() {
        }
        
        public getDetalleByIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updDetalle", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class updDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int Cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int Total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int IdStock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int IdVenta;
        
        public updDetalleRequest() {
        }
        
        public updDetalleRequest(int id, int Cantidad, int Total, int IdStock, int IdVenta) {
            this.id = id;
            this.Cantidad = Cantidad;
            this.Total = Total;
            this.IdStock = IdStock;
            this.IdVenta = IdVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updDetalleResponse", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class updDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public updDetalleResponse() {
        }
        
        public updDetalleResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarDetalleByIdVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarDetalleByIdVenta", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequestBody Body;
        
        public ListarDetalleByIdVentaRequest() {
        }
        
        public ListarDetalleByIdVentaRequest(AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ListarDetalleByIdVentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdVenta;
        
        public ListarDetalleByIdVentaRequestBody() {
        }
        
        public ListarDetalleByIdVentaRequestBody(int IdVenta) {
            this.IdVenta = IdVenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarDetalleByIdVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarDetalleByIdVentaResponse", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaResponseBody Body;
        
        public ListarDetalleByIdVentaResponse() {
        }
        
        public ListarDetalleByIdVentaResponse(AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ListarDetalleByIdVentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ListarDetalleByIdVentaResponseBody() {
        }
        
        public ListarDetalleByIdVentaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductoUsuario", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequestBody Body;
        
        public getProductoUsuarioRequest() {
        }
        
        public getProductoUsuarioRequest(AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getProductoUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rutproductor;
        
        public getProductoUsuarioRequestBody() {
        }
        
        public getProductoUsuarioRequestBody(int Rutproductor) {
            this.Rutproductor = Rutproductor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductoUsuarioResponse", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioResponseBody Body;
        
        public getProductoUsuarioResponse() {
        }
        
        public getProductoUsuarioResponse(AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getProductoUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getProductoUsuarioResponseBody() {
        }
        
        public getProductoUsuarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStockByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStockById", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequestBody Body;
        
        public getStockByIdRequest() {
        }
        
        public getStockByIdRequest(AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getStockByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdStock;
        
        public getStockByIdRequestBody() {
        }
        
        public getStockByIdRequestBody(int IdStock) {
            this.IdStock = IdStock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStockByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStockByIdResponse", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.getStockByIdResponseBody Body;
        
        public getStockByIdResponse() {
        }
        
        public getStockByIdResponse(AppWeb_FrutosFrescos.wsFrutos2.getStockByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getStockByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getStockByIdResponseBody() {
        }
        
        public getStockByIdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStockRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStock", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.getStockRequestBody Body;
        
        public getStockRequest() {
        }
        
        public getStockRequest(AppWeb_FrutosFrescos.wsFrutos2.getStockRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getStockRequestBody {
        
        public getStockRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStockResponse", Namespace="http://wspack/", Order=0)]
        public AppWeb_FrutosFrescos.wsFrutos2.getStockResponseBody Body;
        
        public getStockResponse() {
        }
        
        public getStockResponse(AppWeb_FrutosFrescos.wsFrutos2.getStockResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getStockResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getStockResponseBody() {
        }
        
        public getStockResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsFrutos2Channel : AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsFrutos2Client : System.ServiceModel.ClientBase<AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2>, AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2 {
        
        public wsFrutos2Client() {
        }
        
        public wsFrutos2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsFrutos2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFrutos2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFrutos2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWeb_FrutosFrescos.wsFrutos2.insDetalleResponse AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.insDetalle(AppWeb_FrutosFrescos.wsFrutos2.insDetalleRequest request) {
            return base.Channel.insDetalle(request);
        }
        
        public bool insDetalle(int Cantidad, int Total, int IdStock, int IdVenta) {
            AppWeb_FrutosFrescos.wsFrutos2.insDetalleRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.insDetalleRequest();
            inValue.Cantidad = Cantidad;
            inValue.Total = Total;
            inValue.IdStock = IdStock;
            inValue.IdVenta = IdVenta;
            AppWeb_FrutosFrescos.wsFrutos2.insDetalleResponse retVal = ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).insDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.insDetalleResponse> AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.insDetalleAsync(AppWeb_FrutosFrescos.wsFrutos2.insDetalleRequest request) {
            return base.Channel.insDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.insDetalleResponse> insDetalleAsync(int Cantidad, int Total, int IdStock, int IdVenta) {
            AppWeb_FrutosFrescos.wsFrutos2.insDetalleRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.insDetalleRequest();
            inValue.Cantidad = Cantidad;
            inValue.Total = Total;
            inValue.IdStock = IdStock;
            inValue.IdVenta = IdVenta;
            return ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).insDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWeb_FrutosFrescos.wsFrutos2.delVentaResponse AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.delVenta(AppWeb_FrutosFrescos.wsFrutos2.delVentaRequest request) {
            return base.Channel.delVenta(request);
        }
        
        public bool delVenta(int Id) {
            AppWeb_FrutosFrescos.wsFrutos2.delVentaRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.delVentaRequest();
            inValue.Id = Id;
            AppWeb_FrutosFrescos.wsFrutos2.delVentaResponse retVal = ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).delVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.delVentaResponse> AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.delVentaAsync(AppWeb_FrutosFrescos.wsFrutos2.delVentaRequest request) {
            return base.Channel.delVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.delVentaResponse> delVentaAsync(int Id) {
            AppWeb_FrutosFrescos.wsFrutos2.delVentaRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.delVentaRequest();
            inValue.Id = Id;
            return ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).delVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWeb_FrutosFrescos.wsFrutos2.delDetalleResponse AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.delDetalle(AppWeb_FrutosFrescos.wsFrutos2.delDetalleRequest request) {
            return base.Channel.delDetalle(request);
        }
        
        public bool delDetalle(int id) {
            AppWeb_FrutosFrescos.wsFrutos2.delDetalleRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.delDetalleRequest();
            inValue.id = id;
            AppWeb_FrutosFrescos.wsFrutos2.delDetalleResponse retVal = ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).delDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.delDetalleResponse> AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.delDetalleAsync(AppWeb_FrutosFrescos.wsFrutos2.delDetalleRequest request) {
            return base.Channel.delDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.delDetalleResponse> delDetalleAsync(int id) {
            AppWeb_FrutosFrescos.wsFrutos2.delDetalleRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.delDetalleRequest();
            inValue.id = id;
            return ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).delDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdResponse AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.getDetalleById(AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequest request) {
            return base.Channel.getDetalleById(request);
        }
        
        public string getDetalleById(int IdDetalle) {
            AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequestBody();
            inValue.Body.IdDetalle = IdDetalle;
            AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdResponse retVal = ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).getDetalleById(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdResponse> AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.getDetalleByIdAsync(AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequest request) {
            return base.Channel.getDetalleByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdResponse> getDetalleByIdAsync(int IdDetalle) {
            AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.getDetalleByIdRequestBody();
            inValue.Body.IdDetalle = IdDetalle;
            return ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).getDetalleByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWeb_FrutosFrescos.wsFrutos2.updDetalleResponse AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.updDetalle(AppWeb_FrutosFrescos.wsFrutos2.updDetalleRequest request) {
            return base.Channel.updDetalle(request);
        }
        
        public bool updDetalle(int id, int Cantidad, int Total, int IdStock, int IdVenta) {
            AppWeb_FrutosFrescos.wsFrutos2.updDetalleRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.updDetalleRequest();
            inValue.id = id;
            inValue.Cantidad = Cantidad;
            inValue.Total = Total;
            inValue.IdStock = IdStock;
            inValue.IdVenta = IdVenta;
            AppWeb_FrutosFrescos.wsFrutos2.updDetalleResponse retVal = ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).updDetalle(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.updDetalleResponse> AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.updDetalleAsync(AppWeb_FrutosFrescos.wsFrutos2.updDetalleRequest request) {
            return base.Channel.updDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.updDetalleResponse> updDetalleAsync(int id, int Cantidad, int Total, int IdStock, int IdVenta) {
            AppWeb_FrutosFrescos.wsFrutos2.updDetalleRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.updDetalleRequest();
            inValue.id = id;
            inValue.Cantidad = Cantidad;
            inValue.Total = Total;
            inValue.IdStock = IdStock;
            inValue.IdVenta = IdVenta;
            return ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).updDetalleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaResponse AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.ListarDetalleByIdVenta(AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequest request) {
            return base.Channel.ListarDetalleByIdVenta(request);
        }
        
        public string ListarDetalleByIdVenta(int IdVenta) {
            AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequestBody();
            inValue.Body.IdVenta = IdVenta;
            AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaResponse retVal = ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).ListarDetalleByIdVenta(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaResponse> AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.ListarDetalleByIdVentaAsync(AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequest request) {
            return base.Channel.ListarDetalleByIdVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaResponse> ListarDetalleByIdVentaAsync(int IdVenta) {
            AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.ListarDetalleByIdVentaRequestBody();
            inValue.Body.IdVenta = IdVenta;
            return ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).ListarDetalleByIdVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioResponse AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.getProductoUsuario(AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequest request) {
            return base.Channel.getProductoUsuario(request);
        }
        
        public string getProductoUsuario(int Rutproductor) {
            AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequestBody();
            inValue.Body.Rutproductor = Rutproductor;
            AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioResponse retVal = ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).getProductoUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioResponse> AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.getProductoUsuarioAsync(AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequest request) {
            return base.Channel.getProductoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioResponse> getProductoUsuarioAsync(int Rutproductor) {
            AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.getProductoUsuarioRequestBody();
            inValue.Body.Rutproductor = Rutproductor;
            return ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).getProductoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWeb_FrutosFrescos.wsFrutos2.getStockByIdResponse AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.getStockById(AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequest request) {
            return base.Channel.getStockById(request);
        }
        
        public string getStockById(int IdStock) {
            AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequestBody();
            inValue.Body.IdStock = IdStock;
            AppWeb_FrutosFrescos.wsFrutos2.getStockByIdResponse retVal = ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).getStockById(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getStockByIdResponse> AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.getStockByIdAsync(AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequest request) {
            return base.Channel.getStockByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getStockByIdResponse> getStockByIdAsync(int IdStock) {
            AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.getStockByIdRequestBody();
            inValue.Body.IdStock = IdStock;
            return ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).getStockByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppWeb_FrutosFrescos.wsFrutos2.getStockResponse AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.getStock(AppWeb_FrutosFrescos.wsFrutos2.getStockRequest request) {
            return base.Channel.getStock(request);
        }
        
        public string getStock() {
            AppWeb_FrutosFrescos.wsFrutos2.getStockRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.getStockRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.getStockRequestBody();
            AppWeb_FrutosFrescos.wsFrutos2.getStockResponse retVal = ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).getStock(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getStockResponse> AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2.getStockAsync(AppWeb_FrutosFrescos.wsFrutos2.getStockRequest request) {
            return base.Channel.getStockAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppWeb_FrutosFrescos.wsFrutos2.getStockResponse> getStockAsync() {
            AppWeb_FrutosFrescos.wsFrutos2.getStockRequest inValue = new AppWeb_FrutosFrescos.wsFrutos2.getStockRequest();
            inValue.Body = new AppWeb_FrutosFrescos.wsFrutos2.getStockRequestBody();
            return ((AppWeb_FrutosFrescos.wsFrutos2.wsFrutos2)(this)).getStockAsync(inValue);
        }
    }
}
