//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Feria_Desktop.wsFrutos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wspack/", ConfigurationName="wsFrutos.wsFrutos")]
    public interface wsFrutos {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://wspack/).
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/RecuperarContrasenaRequest", ReplyAction="http://wspack/wsFrutos/RecuperarContrasenaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Feria_Desktop.wsFrutos.RecuperarContrasenaResponse RecuperarContrasena(Feria_Desktop.wsFrutos.RecuperarContrasenaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/RecuperarContrasenaRequest", ReplyAction="http://wspack/wsFrutos/RecuperarContrasenaResponse")]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.RecuperarContrasenaResponse> RecuperarContrasenaAsync(Feria_Desktop.wsFrutos.RecuperarContrasenaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Password del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/LoginRequest", ReplyAction="http://wspack/wsFrutos/LoginResponse")]
        Feria_Desktop.wsFrutos.LoginResponse Login(Feria_Desktop.wsFrutos.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/LoginRequest", ReplyAction="http://wspack/wsFrutos/LoginResponse")]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.LoginResponse> LoginAsync(Feria_Desktop.wsFrutos.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getTipoUsuarioByTipoRequest", ReplyAction="http://wspack/wsFrutos/getTipoUsuarioByTipoResponse")]
        Feria_Desktop.wsFrutos.getTipoUsuarioByTipoResponse getTipoUsuarioByTipo(Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getTipoUsuarioByTipoRequest", ReplyAction="http://wspack/wsFrutos/getTipoUsuarioByTipoResponse")]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getTipoUsuarioByTipoResponse> getTipoUsuarioByTipoAsync(Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getUsuariosByTipoRequest", ReplyAction="http://wspack/wsFrutos/getUsuariosByTipoResponse")]
        Feria_Desktop.wsFrutos.getUsuariosByTipoResponse getUsuariosByTipo(Feria_Desktop.wsFrutos.getUsuariosByTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getUsuariosByTipoRequest", ReplyAction="http://wspack/wsFrutos/getUsuariosByTipoResponse")]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getUsuariosByTipoResponse> getUsuariosByTipoAsync(Feria_Desktop.wsFrutos.getUsuariosByTipoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getProdByTipoRequest", ReplyAction="http://wspack/wsFrutos/getProdByTipoResponse")]
        Feria_Desktop.wsFrutos.getProdByTipoResponse getProdByTipo(Feria_Desktop.wsFrutos.getProdByTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getProdByTipoRequest", ReplyAction="http://wspack/wsFrutos/getProdByTipoResponse")]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getProdByTipoResponse> getProdByTipoAsync(Feria_Desktop.wsFrutos.getProdByTipoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getUsuariosRequest", ReplyAction="http://wspack/wsFrutos/getUsuariosResponse")]
        Feria_Desktop.wsFrutos.getUsuariosResponse getUsuarios(Feria_Desktop.wsFrutos.getUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getUsuariosRequest", ReplyAction="http://wspack/wsFrutos/getUsuariosResponse")]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getUsuariosResponse> getUsuariosAsync(Feria_Desktop.wsFrutos.getUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getTipoProdRequest", ReplyAction="http://wspack/wsFrutos/getTipoProdResponse")]
        Feria_Desktop.wsFrutos.getTipoProdResponse getTipoProd(Feria_Desktop.wsFrutos.getTipoProdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/getTipoProdRequest", ReplyAction="http://wspack/wsFrutos/getTipoProdResponse")]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getTipoProdResponse> getTipoProdAsync(Feria_Desktop.wsFrutos.getTipoProdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/ListarVentasByVendedorRequest", ReplyAction="http://wspack/wsFrutos/ListarVentasByVendedorResponse")]
        Feria_Desktop.wsFrutos.ListarVentasByVendedorResponse ListarVentasByVendedor(Feria_Desktop.wsFrutos.ListarVentasByVendedorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wspack/wsFrutos/ListarVentasByVendedorRequest", ReplyAction="http://wspack/wsFrutos/ListarVentasByVendedorResponse")]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.ListarVentasByVendedorResponse> ListarVentasByVendedorAsync(Feria_Desktop.wsFrutos.ListarVentasByVendedorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarContrasena", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class RecuperarContrasenaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int Rut;
        
        public RecuperarContrasenaRequest() {
        }
        
        public RecuperarContrasenaRequest(int Rut) {
            this.Rut = Rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperarContrasenaResponse", WrapperNamespace="http://wspack/", IsWrapped=true)]
    public partial class RecuperarContrasenaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public RecuperarContrasenaResponse() {
        }
        
        public RecuperarContrasenaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Feria_Desktop.wsFrutos.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(int Rut, string Password) {
            this.Rut = Rut;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Feria_Desktop.wsFrutos.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTipoUsuarioByTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTipoUsuarioByTipo", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequestBody Body;
        
        public getTipoUsuarioByTipoRequest() {
        }
        
        public getTipoUsuarioByTipoRequest(Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getTipoUsuarioByTipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoUsuario;
        
        public getTipoUsuarioByTipoRequestBody() {
        }
        
        public getTipoUsuarioByTipoRequestBody(int tipoUsuario) {
            this.tipoUsuario = tipoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTipoUsuarioByTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTipoUsuarioByTipoResponse", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getTipoUsuarioByTipoResponseBody Body;
        
        public getTipoUsuarioByTipoResponse() {
        }
        
        public getTipoUsuarioByTipoResponse(Feria_Desktop.wsFrutos.getTipoUsuarioByTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getTipoUsuarioByTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTipoUsuarioByTipoResponseBody() {
        }
        
        public getTipoUsuarioByTipoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsuariosByTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsuariosByTipo", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getUsuariosByTipoRequestBody Body;
        
        public getUsuariosByTipoRequest() {
        }
        
        public getUsuariosByTipoRequest(Feria_Desktop.wsFrutos.getUsuariosByTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getUsuariosByTipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoUsuario;
        
        public getUsuariosByTipoRequestBody() {
        }
        
        public getUsuariosByTipoRequestBody(int tipoUsuario) {
            this.tipoUsuario = tipoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsuariosByTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsuariosByTipoResponse", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getUsuariosByTipoResponseBody Body;
        
        public getUsuariosByTipoResponse() {
        }
        
        public getUsuariosByTipoResponse(Feria_Desktop.wsFrutos.getUsuariosByTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getUsuariosByTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getUsuariosByTipoResponseBody() {
        }
        
        public getUsuariosByTipoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProdByTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProdByTipo", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getProdByTipoRequestBody Body;
        
        public getProdByTipoRequest() {
        }
        
        public getProdByTipoRequest(Feria_Desktop.wsFrutos.getProdByTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getProdByTipoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tipoProducto;
        
        public getProdByTipoRequestBody() {
        }
        
        public getProdByTipoRequestBody(int tipoProducto) {
            this.tipoProducto = tipoProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProdByTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProdByTipoResponse", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getProdByTipoResponseBody Body;
        
        public getProdByTipoResponse() {
        }
        
        public getProdByTipoResponse(Feria_Desktop.wsFrutos.getProdByTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getProdByTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getProdByTipoResponseBody() {
        }
        
        public getProdByTipoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsuarios", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getUsuariosRequestBody Body;
        
        public getUsuariosRequest() {
        }
        
        public getUsuariosRequest(Feria_Desktop.wsFrutos.getUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUsuariosRequestBody {
        
        public getUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsuariosResponse", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getUsuariosResponseBody Body;
        
        public getUsuariosResponse() {
        }
        
        public getUsuariosResponse(Feria_Desktop.wsFrutos.getUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getUsuariosResponseBody() {
        }
        
        public getUsuariosResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTipoProdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTipoProd", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getTipoProdRequestBody Body;
        
        public getTipoProdRequest() {
        }
        
        public getTipoProdRequest(Feria_Desktop.wsFrutos.getTipoProdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getTipoProdRequestBody {
        
        public getTipoProdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTipoProdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTipoProdResponse", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.getTipoProdResponseBody Body;
        
        public getTipoProdResponse() {
        }
        
        public getTipoProdResponse(Feria_Desktop.wsFrutos.getTipoProdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getTipoProdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getTipoProdResponseBody() {
        }
        
        public getTipoProdResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarVentasByVendedorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarVentasByVendedor", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.ListarVentasByVendedorRequestBody Body;
        
        public ListarVentasByVendedorRequest() {
        }
        
        public ListarVentasByVendedorRequest(Feria_Desktop.wsFrutos.ListarVentasByVendedorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ListarVentasByVendedorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rut;
        
        public ListarVentasByVendedorRequestBody() {
        }
        
        public ListarVentasByVendedorRequestBody(int Rut) {
            this.Rut = Rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarVentasByVendedorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarVentasByVendedorResponse", Namespace="http://wspack/", Order=0)]
        public Feria_Desktop.wsFrutos.ListarVentasByVendedorResponseBody Body;
        
        public ListarVentasByVendedorResponse() {
        }
        
        public ListarVentasByVendedorResponse(Feria_Desktop.wsFrutos.ListarVentasByVendedorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ListarVentasByVendedorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ListarVentasByVendedorResponseBody() {
        }
        
        public ListarVentasByVendedorResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsFrutosChannel : Feria_Desktop.wsFrutos.wsFrutos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsFrutosClient : System.ServiceModel.ClientBase<Feria_Desktop.wsFrutos.wsFrutos>, Feria_Desktop.wsFrutos.wsFrutos {
        
        public wsFrutosClient() {
        }
        
        public wsFrutosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsFrutosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFrutosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsFrutosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Feria_Desktop.wsFrutos.RecuperarContrasenaResponse Feria_Desktop.wsFrutos.wsFrutos.RecuperarContrasena(Feria_Desktop.wsFrutos.RecuperarContrasenaRequest request) {
            return base.Channel.RecuperarContrasena(request);
        }
        
        public bool RecuperarContrasena(int Rut) {
            Feria_Desktop.wsFrutos.RecuperarContrasenaRequest inValue = new Feria_Desktop.wsFrutos.RecuperarContrasenaRequest();
            inValue.Rut = Rut;
            Feria_Desktop.wsFrutos.RecuperarContrasenaResponse retVal = ((Feria_Desktop.wsFrutos.wsFrutos)(this)).RecuperarContrasena(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.RecuperarContrasenaResponse> Feria_Desktop.wsFrutos.wsFrutos.RecuperarContrasenaAsync(Feria_Desktop.wsFrutos.RecuperarContrasenaRequest request) {
            return base.Channel.RecuperarContrasenaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.RecuperarContrasenaResponse> RecuperarContrasenaAsync(int Rut) {
            Feria_Desktop.wsFrutos.RecuperarContrasenaRequest inValue = new Feria_Desktop.wsFrutos.RecuperarContrasenaRequest();
            inValue.Rut = Rut;
            return ((Feria_Desktop.wsFrutos.wsFrutos)(this)).RecuperarContrasenaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Feria_Desktop.wsFrutos.LoginResponse Feria_Desktop.wsFrutos.wsFrutos.Login(Feria_Desktop.wsFrutos.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(int Rut, string Password) {
            Feria_Desktop.wsFrutos.LoginRequest inValue = new Feria_Desktop.wsFrutos.LoginRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.LoginRequestBody();
            inValue.Body.Rut = Rut;
            inValue.Body.Password = Password;
            Feria_Desktop.wsFrutos.LoginResponse retVal = ((Feria_Desktop.wsFrutos.wsFrutos)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.LoginResponse> Feria_Desktop.wsFrutos.wsFrutos.LoginAsync(Feria_Desktop.wsFrutos.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.LoginResponse> LoginAsync(int Rut, string Password) {
            Feria_Desktop.wsFrutos.LoginRequest inValue = new Feria_Desktop.wsFrutos.LoginRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.LoginRequestBody();
            inValue.Body.Rut = Rut;
            inValue.Body.Password = Password;
            return ((Feria_Desktop.wsFrutos.wsFrutos)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Feria_Desktop.wsFrutos.getTipoUsuarioByTipoResponse Feria_Desktop.wsFrutos.wsFrutos.getTipoUsuarioByTipo(Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequest request) {
            return base.Channel.getTipoUsuarioByTipo(request);
        }
        
        public string getTipoUsuarioByTipo(int tipoUsuario) {
            Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequest inValue = new Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequestBody();
            inValue.Body.tipoUsuario = tipoUsuario;
            Feria_Desktop.wsFrutos.getTipoUsuarioByTipoResponse retVal = ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getTipoUsuarioByTipo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getTipoUsuarioByTipoResponse> Feria_Desktop.wsFrutos.wsFrutos.getTipoUsuarioByTipoAsync(Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequest request) {
            return base.Channel.getTipoUsuarioByTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getTipoUsuarioByTipoResponse> getTipoUsuarioByTipoAsync(int tipoUsuario) {
            Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequest inValue = new Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getTipoUsuarioByTipoRequestBody();
            inValue.Body.tipoUsuario = tipoUsuario;
            return ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getTipoUsuarioByTipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Feria_Desktop.wsFrutos.getUsuariosByTipoResponse Feria_Desktop.wsFrutos.wsFrutos.getUsuariosByTipo(Feria_Desktop.wsFrutos.getUsuariosByTipoRequest request) {
            return base.Channel.getUsuariosByTipo(request);
        }
        
        public string getUsuariosByTipo(int tipoUsuario) {
            Feria_Desktop.wsFrutos.getUsuariosByTipoRequest inValue = new Feria_Desktop.wsFrutos.getUsuariosByTipoRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getUsuariosByTipoRequestBody();
            inValue.Body.tipoUsuario = tipoUsuario;
            Feria_Desktop.wsFrutos.getUsuariosByTipoResponse retVal = ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getUsuariosByTipo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getUsuariosByTipoResponse> Feria_Desktop.wsFrutos.wsFrutos.getUsuariosByTipoAsync(Feria_Desktop.wsFrutos.getUsuariosByTipoRequest request) {
            return base.Channel.getUsuariosByTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getUsuariosByTipoResponse> getUsuariosByTipoAsync(int tipoUsuario) {
            Feria_Desktop.wsFrutos.getUsuariosByTipoRequest inValue = new Feria_Desktop.wsFrutos.getUsuariosByTipoRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getUsuariosByTipoRequestBody();
            inValue.Body.tipoUsuario = tipoUsuario;
            return ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getUsuariosByTipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Feria_Desktop.wsFrutos.getProdByTipoResponse Feria_Desktop.wsFrutos.wsFrutos.getProdByTipo(Feria_Desktop.wsFrutos.getProdByTipoRequest request) {
            return base.Channel.getProdByTipo(request);
        }
        
        public string getProdByTipo(int tipoProducto) {
            Feria_Desktop.wsFrutos.getProdByTipoRequest inValue = new Feria_Desktop.wsFrutos.getProdByTipoRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getProdByTipoRequestBody();
            inValue.Body.tipoProducto = tipoProducto;
            Feria_Desktop.wsFrutos.getProdByTipoResponse retVal = ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getProdByTipo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getProdByTipoResponse> Feria_Desktop.wsFrutos.wsFrutos.getProdByTipoAsync(Feria_Desktop.wsFrutos.getProdByTipoRequest request) {
            return base.Channel.getProdByTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getProdByTipoResponse> getProdByTipoAsync(int tipoProducto) {
            Feria_Desktop.wsFrutos.getProdByTipoRequest inValue = new Feria_Desktop.wsFrutos.getProdByTipoRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getProdByTipoRequestBody();
            inValue.Body.tipoProducto = tipoProducto;
            return ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getProdByTipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Feria_Desktop.wsFrutos.getUsuariosResponse Feria_Desktop.wsFrutos.wsFrutos.getUsuarios(Feria_Desktop.wsFrutos.getUsuariosRequest request) {
            return base.Channel.getUsuarios(request);
        }
        
        public string getUsuarios() {
            Feria_Desktop.wsFrutos.getUsuariosRequest inValue = new Feria_Desktop.wsFrutos.getUsuariosRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getUsuariosRequestBody();
            Feria_Desktop.wsFrutos.getUsuariosResponse retVal = ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getUsuarios(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getUsuariosResponse> Feria_Desktop.wsFrutos.wsFrutos.getUsuariosAsync(Feria_Desktop.wsFrutos.getUsuariosRequest request) {
            return base.Channel.getUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getUsuariosResponse> getUsuariosAsync() {
            Feria_Desktop.wsFrutos.getUsuariosRequest inValue = new Feria_Desktop.wsFrutos.getUsuariosRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getUsuariosRequestBody();
            return ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Feria_Desktop.wsFrutos.getTipoProdResponse Feria_Desktop.wsFrutos.wsFrutos.getTipoProd(Feria_Desktop.wsFrutos.getTipoProdRequest request) {
            return base.Channel.getTipoProd(request);
        }
        
        public string getTipoProd() {
            Feria_Desktop.wsFrutos.getTipoProdRequest inValue = new Feria_Desktop.wsFrutos.getTipoProdRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getTipoProdRequestBody();
            Feria_Desktop.wsFrutos.getTipoProdResponse retVal = ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getTipoProd(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getTipoProdResponse> Feria_Desktop.wsFrutos.wsFrutos.getTipoProdAsync(Feria_Desktop.wsFrutos.getTipoProdRequest request) {
            return base.Channel.getTipoProdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.getTipoProdResponse> getTipoProdAsync() {
            Feria_Desktop.wsFrutos.getTipoProdRequest inValue = new Feria_Desktop.wsFrutos.getTipoProdRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.getTipoProdRequestBody();
            return ((Feria_Desktop.wsFrutos.wsFrutos)(this)).getTipoProdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Feria_Desktop.wsFrutos.ListarVentasByVendedorResponse Feria_Desktop.wsFrutos.wsFrutos.ListarVentasByVendedor(Feria_Desktop.wsFrutos.ListarVentasByVendedorRequest request) {
            return base.Channel.ListarVentasByVendedor(request);
        }
        
        public string ListarVentasByVendedor(int Rut) {
            Feria_Desktop.wsFrutos.ListarVentasByVendedorRequest inValue = new Feria_Desktop.wsFrutos.ListarVentasByVendedorRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.ListarVentasByVendedorRequestBody();
            inValue.Body.Rut = Rut;
            Feria_Desktop.wsFrutos.ListarVentasByVendedorResponse retVal = ((Feria_Desktop.wsFrutos.wsFrutos)(this)).ListarVentasByVendedor(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.ListarVentasByVendedorResponse> Feria_Desktop.wsFrutos.wsFrutos.ListarVentasByVendedorAsync(Feria_Desktop.wsFrutos.ListarVentasByVendedorRequest request) {
            return base.Channel.ListarVentasByVendedorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Feria_Desktop.wsFrutos.ListarVentasByVendedorResponse> ListarVentasByVendedorAsync(int Rut) {
            Feria_Desktop.wsFrutos.ListarVentasByVendedorRequest inValue = new Feria_Desktop.wsFrutos.ListarVentasByVendedorRequest();
            inValue.Body = new Feria_Desktop.wsFrutos.ListarVentasByVendedorRequestBody();
            inValue.Body.Rut = Rut;
            return ((Feria_Desktop.wsFrutos.wsFrutos)(this)).ListarVentasByVendedorAsync(inValue);
        }
    }
}
